- name: Deploy ArgoCD and Prometheus in EKS cluster
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    kubeconfig_path: "{{ lookup('env','KUBECONFIG') }}"

  tasks:

  - name: Install NGINX Ingress Controller
    kubernetes.core.k8s:
      state: present
      src: https://raw.githubusercontent.com/kubernetes/ingress-nginx/main/deploy/static/provider/cloud/deploy.yaml
      kubeconfig: "{{ kubeconfig_path }}"

  - name: Wait for ingress controller
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: ingress-nginx
      kubeconfig: "{{ kubeconfig_path }}"
    register: ingress_pods
    retries: 30
    delay: 10
    until: >
      ingress_pods.resources | selectattr('status.phase','equalto','Running') | list | length > 1

  - name: Create ArgoCD namespace
    kubernetes.core.k8s:
      name: argocd
      api_version: v1
      kind: Namespace
      state: present
      kubeconfig: "{{ kubeconfig_path }}"

  - name: Install ArgoCD
    kubernetes.core.k8s:
      state: present
      src: https://raw.githubusercontent.com/argoproj/argo-cd/stable/manifests/install.yaml
      namespace: argocd
      kubeconfig: "{{ kubeconfig_path }}"

  - name: Wait for ArgoCD pods
    kubernetes.core.k8s_info:
      kind: Pod
      namespace: argocd
      kubeconfig: "{{ kubeconfig_path }}"
    register: pod_status
    retries: 30
    delay: 10
    until: >
      pod_status.resources | selectattr('status.phase','equalto','Running') | list | length > 2

  - name: Create Prometheus namespace
    kubernetes.core.k8s:
      name: prometheus
      api_version: v1
      kind: Namespace
      state: present
      kubeconfig: "{{ kubeconfig_path }}"

  - name: Install Helm
    ansible.builtin.shell: |
      curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | VERIFY_CHECKSUM=false bash

  - name: Add Prometheus Helm repository
    ansible.builtin.command:
      cmd: helm repo add prometheus-community https://prometheus-community.github.io/helm-charts
    environment:
      KUBECONFIG: "{{ kubeconfig_path }}"

  - name: Add Grafana Helm repository
    ansible.builtin.command:
      cmd: helm repo add grafana-community https://grafana-community.github.io/helm-charts

  - name: Update Helm repositories
    ansible.builtin.command:
      cmd: helm repo update
    environment:
      KUBECONFIG: "{{ kubeconfig_path }}"

  - name: Install Prometheus
    ansible.builtin.command: >
      helm upgrade -i prometheus prometheus-community/prometheus
      --namespace prometheus
      --set alertmanager.persistence.storageClass="gp2"
      --set server.persistentVolume.storageClass="gp2"
    environment:
      KUBECONFIG: "{{ kubeconfig_path }}"

  - name: Install Grafana
    ansible.builtin.command: >
      helm upgrade -i grafana grafana-community/grafana
      --namespace prometheus
      --set service.type=LoadBalancer
    environment:
      KUBECONFIG: "{{ kubeconfig_path }}"


  - name: Verify Prometheus pods
    ansible.builtin.command:
      cmd: kubectl get pods -n prometheus
    register: pods

  - name: Show pods
    debug:
      var: pods.stdout
  